# Application
spring.application.name=hazina

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/hazina
spring.datasource.username=hazina_user
spring.datasource.password=hazina_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080

# JWT
jwt.secret=aGF6aW5hLWp3dC1zZWNyZXQta2V5LWZvci1hdXRoZW50aWNhdGlvbi1jaGFuZ2UtaW4tcHJvZC1taW4tMjU2Yml0
jwt.expiration=86400000

# Logging
logging.level.com.accounting=DEBUG
logging.level.org.flywaydb=DEBUG